In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("train.csv")
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404290 entries, 0 to 404289
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   id            404290 non-null  int64
 1   qid1          404290 non-null  int64
 2   qid2          404290 non-null  int64
 3   question1     404289 non-null  object
 4   question2     404288 non-null  object
 5   is_duplicate  404290 non-null  int64
dtypes: int64(4), object(2)
memory usage: 18.5+ MB

In [5]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       1
question2       2
is_duplicate    0
dtype: int64

In [6]:
df.shape

(404290, 6)

In [8]:
df = df.dropna(subset = ['question1','question2'])

In [9]:
df = df.sample(30000, random_state = 42)

In [10]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [12]:
df.shape

(30000, 6)

In [13]:
df.sample(10)

,id,qid1,qid2,question1,question2,is_duplicate
217981,217981,324472,324473,What a header file?,What is a header file?,1
115825,115825,188799,188800,What are the top colleges comes under AIMA MAT?,I have secured a composite score of 707.5 and ...,0
214590,214590,320224,190095,"Find perpendicular unit vectors I, J, K differ...",How old where you when you became a music major?,0
325698,325698,451949,451950,Does delayed choice quantum eraser violate the...,How much math and physics must one know before...,0
215846,215846,290983,114375,How can an introvert make friends?,How do introverts make new friends?,1
217403,217403,323739,323740,Why does a man need women's clothes and makeup...,I am a non-EU citizen and currently holding a ...,0
349155,349155,477802,477803,What is the charge to a merchant for using Pay...,"Will I get any benefits from PayTM, if I use t...",0
272756,272756,123740,60356,How do I start exploring the Deep Web?,What is deep web and dark web? And how to acce...,1
353991,353991,12304,60956,What are some of your New Year's resolutions f...,What are some of the best New Years resolution...,1
65706,65706,113993,113994,Is mechanical engineering a dead field today?,Is mechanical engineering dead?,1

In [15]:
import re 
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/om-codex/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [16]:
def cleanup(text):
    text = text.lower()
    text = re.sub(r"[^\w\s]", "",text)
    tokens = word_tokenize(text)

    return tokens

In [18]:
df['q1_tokens'] = df['question1'].apply(cleanup)
df['q2_tokens'] = df['question2'].apply(cleanup)

In [20]:
df[['question1','q1_tokens','question2','q2_tokens']].head()

,question1,q1_tokens,question2,q2_tokens
8067,How do I play Pokémon GO in Korea?,"[how, do, i, play, pokémon, go, in, korea]",How do I play Pokémon GO in China?,"[how, do, i, play, pokémon, go, in, china]"
224279,Will a breathing treatment help a cough?,"[will, a, breathing, treatment, help, a, cough]",How can I help someone that is unconscious but...,"[how, can, i, help, someone, that, is, unconsc..."
252452,Is Kellyanne Conway annoying in your opinion?,"[is, kellyanne, conway, annoying, in, your, op...",Did Kellyanne Conway really imply that we shou...,"[did, kellyanne, conway, really, imply, that, ..."
174039,How do you rate (1-10) and review Maruti Baleno?,"[how, do, you, rate, 110, and, review, maruti,...",What career options does one have after comple...,"[what, career, options, does, one, have, after..."
384863,What are some good books on marketing?,"[what, are, some, good, books, on, marketing]",What are some of the best books ever written a...,"[what, are, some, of, the, best, books, ever, ..."

In [22]:
df['q1_len'] = df['q1_tokens'].apply(len)
df['q2_len'] = df['q2_tokens'].apply(len)
df.head()

,id,qid1,qid2,question1,question2,is_duplicate,q1_tokens,q2_tokens,q1_len,q2_len
8067,8067,15738,15739,How do I play Pokémon GO in Korea?,How do I play Pokémon GO in China?,0,"[how, do, i, play, pokémon, go, in, korea]","[how, do, i, play, pokémon, go, in, china]",8,8
224279,224279,332326,332327,Will a breathing treatment help a cough?,How can I help someone that is unconscious but...,0,"[will, a, breathing, treatment, help, a, cough]","[how, can, i, help, someone, that, is, unconsc...",7,11
252452,252452,336023,366789,Is Kellyanne Conway annoying in your opinion?,Did Kellyanne Conway really imply that we shou...,0,"[is, kellyanne, conway, annoying, in, your, op...","[did, kellyanne, conway, really, imply, that, ...",7,21
174039,174039,268330,268331,How do you rate (1-10) and review Maruti Baleno?,What career options does one have after comple...,0,"[how, do, you, rate, 110, and, review, maruti,...","[what, career, options, does, one, have, after...",9,20
384863,384863,28901,233483,What are some good books on marketing?,What are some of the best books ever written a...,1,"[what, are, some, good, books, on, marketing]","[what, are, some, of, the, best, books, ever, ...",7,11

In [23]:
print(df['q1_len'].describe())

count    30000.000000
mean        10.946733
std          5.408937
min          1.000000
25%          7.000000
50%         10.000000
75%         13.000000
max         79.000000
Name: q1_len, dtype: float64

In [25]:
from collections import Counter

all_tokens = []

for tokens in df['q1_tokens']:
    all_tokens.extend(tokens)
for tokens in df['q2_tokens']:
    all_tokens.extend(tokens)

token_counts = Counter(all_tokens)

MAX_VOCAB = 20000

most_common = token_counts.most_common(MAX_VOCAB - 2)

vocab_words = [w for w, _ in most_common]

word2idx = {"<PAD>": 0, "<UNK>":1}
for i, w in enumerate(vocab_words, start = 2):
    word2idx[w] = i

idx2word = {i: w for w, i in word2idx.items()}

vocab_size = len(word2idx)
print("Vocab Size: ",vocab_size)

Vocab Size:  20000

In [26]:
def tokens_to_ids(tokens, word2idx):
    return [word2idx.get(t, word2idx["<UNK>"]) for t in tokens]

df["q1_ids"] = df["q1_tokens"].apply(lambda x: tokens_to_ids(x, word2idx))
df["q2_ids"] = df["q2_tokens"].apply(lambda x: tokens_to_ids(x, word2idx))

In [27]:
import numpy as np

MAX_LEN = 20

def pad_truncate(seq, max_len=MAX_LEN, pad_value=0):
    if len(seq) >= max_len:
        return seq[:max_len]
    else:
        return seq + [pad_value] * (max_len - len(seq))

df["q1_seq"] = df["q1_ids"].apply(pad_truncate)
df["q2_seq"] = df["q2_ids"].apply(pad_truncate)

In [28]:
X1 = np.array(df["q1_seq"].tolist(), dtype=np.int64)
X2 = np.array(df["q2_seq"].tolist(), dtype=np.int64)
y  = df["is_duplicate"].values.astype(np.float32)

print(X1.shape, X2.shape, y.shape)

(30000, 20) (30000, 20) (30000,)

In [29]:
# Check PAD usage
print("Example q1_seq:", X1[0])
print("PAD count in sample:", (X1[0] == 0).sum())

# Check UNK presence
unk_idx = word2idx["<UNK>"]
print("UNK count in sample:", (X1[0] == unk_idx).sum())

Example q1_seq: [   5   10    6  301 1024  126    9 1206    0    0    0    0    0    0
    0    0    0    0    0    0]
PAD count in sample: 12
UNK count in sample: 0

In [30]:
i = 0
print("Q1:", df.iloc[i]["question1"])
print("Tokens:", df.iloc[i]["q1_tokens"])
print("Seq:", df.iloc[i]["q1_seq"])

Q1: How do I play Pokémon GO in Korea?
Tokens: ['how', 'do', 'i', 'play', 'pokémon', 'go', 'in', 'korea']
Seq: [5, 10, 6, 301, 1024, 126, 9, 1206, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [31]:
import torch
from torch.utils.data import Dataset, DataLoader

In [32]:
class QuoraDataset(Dataset):
    
    def __init__(self, X1, X2, y):
        self.X1 = torch.tensor(X1, dtype=torch.long)
        self.X2 = torch.tensor(X2, dtype=torch.long)
        self.y  = torch.tensor(y, dtype=torch.float32)
        
    def __len__(self):
        return len(self.y)
    
    def __getitem__(self, idx):
        return self.X1[idx], self.X2[idx], self.y[idx]

In [33]:
from sklearn.model_selection import train_test_split

X1_train, X1_val, X2_train, X2_val, y_train, y_val = train_test_split(
    X1, X2, y, test_size=0.2, random_state=42
)

In [34]:
train_dataset = QuoraDataset(X1_train, X2_train, y_train)
val_dataset   = QuoraDataset(X1_val, X2_val, y_val)

In [35]:
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=64)

In [36]:
for q1, q2, label in train_loader:
    print(q1.shape)
    print(q2.shape)
    print(label.shape)
    break

torch.Size([64, 20])
torch.Size([64, 20])
torch.Size([64])

In [37]:
import torch.nn as nn

In [38]:
class SiameseLSTM(nn.Module):
    
    def __init__(self, vocab_size, embed_dim, hidden_dim):
        super().__init__()
        
        # Embedding Layer
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        
        # Shared LSTM Encoder
        self.lstm = nn.LSTM(embed_dim, hidden_dim, batch_first=True)
        
        # Final Classifier
        self.fc = nn.Linear(hidden_dim, 1)
        
    def encode(self, x):
        
        # x → embeddings
        emb = self.embedding(x)
        
        # emb → LSTM
        _, (hidden, _) = self.lstm(emb)
        
        # last hidden state
        return hidden[-1]
    
    def forward(self, q1, q2):
        
        v1 = self.encode(q1)
        v2 = self.encode(q2)
        
        diff = torch.abs(v1 - v2)
        
        output = self.fc(diff)
        
        return torch.sigmoid(output).squeeze()

In [39]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = SiameseLSTM(
    vocab_size=vocab_size,
    embed_dim=100,
    hidden_dim=128
).to(device)

In [40]:
criterion = nn.BCELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [41]:
def train_epoch(model, loader):
    
    model.train()
    total_loss = 0
    
    for q1, q2, labels in loader:
        
        q1 = q1.to(device)
        q2 = q2.to(device)
        labels = labels.to(device)
        
        preds = model(q1, q2)
        
        loss = criterion(preds, labels)
        
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
        total_loss += loss.item()
    
    return total_loss / len(loader)

In [42]:
def eval_epoch(model, loader):
    
    model.eval()
    total_loss = 0
    
    with torch.no_grad():
        for q1, q2, labels in loader:
            
            q1 = q1.to(device)
            q2 = q2.to(device)
            labels = labels.to(device)
            
            preds = model(q1, q2)
            loss = criterion(preds, labels)
            
            total_loss += loss.item()
    
    return total_loss / len(loader)

In [43]:
epochs = 5

for epoch in range(epochs):
    
    train_loss = train_epoch(model, train_loader)
    val_loss = eval_epoch(model, val_loader)
    
    print(f"Epoch {epoch+1}")
    print("Train Loss:", train_loss)
    print("Val Loss:", val_loss)

Epoch 1
Train Loss: 0.6098938351472218
Val Loss: 0.6017207836217069
Epoch 2
Train Loss: 0.5632460532188416
Val Loss: 0.5766479661490055
Epoch 3
Train Loss: 0.5113391443888347
Val Loss: 0.5531422460966922
Epoch 4
Train Loss: 0.4504904381434123
Val Loss: 0.5478724244427173
Epoch 5
Train Loss: 0.3901503756046295
Val Loss: 0.5561407753761779

In [44]:
model.eval()

for q1, q2, labels in val_loader:
    
    q1 = q1.to(device)
    q2 = q2.to(device)
    
    preds = model(q1, q2)
    
    preds = (preds > 0.5).cpu().numpy()
    
    for i in range(len(preds)):
        if preds[i] != labels[i]:
            print("Q1:", df.iloc[i]["question1"])
            print("Q2:", df.iloc[i]["question2"])
            print("Actual:", labels[i].item())
            print("Pred:", preds[i])
            print()
    
    break

Q1: Will a breathing treatment help a cough?
Q2: How can I help someone that is unconscious but still breathing?
Actual: 0.0
Pred: True

Q1: Is odd even scheme bad for Delhi?
Q2: Is ODD-EVEN scheme good for Delhi?
Actual: 1.0
Pred: False

Q1: What's the probability that a leap year has 53 Sundays?
Q2: What are some unknown facts about Leap Year and 29th Feb ?
Actual: 0.0
Pred: True

Q1: I would like to join member in Connemara Public Library. what is the procedure to follow and also membership fees?
Q2: How do I be a member of the NSD library?
Actual: 1.0
Pred: False

Q1: How can someone control their anger?
Q2: How can a person control anger?
Actual: 1.0
Pred: False

Q1: How exactly is Pradhanmantri Jan Dhan Yojana different from asking people to go and open a bank account in any local branch?
Q2: After the launch of PM Jan Dhan Yojana, what is the total number of bank account holders in India today, both old and new combined? Also how many more accounts need to be opened to cover all families in India?
Actual: 0.0
Pred: True

Q1: What's the best way to get laid in Bangalore?
Q2: How do I get laid in Bangalore?
Actual: 1.0
Pred: False

Q1: What is your New Year Resolution for 2017?
Q2: What is your new year resolution?
Actual: 0.0
Pred: True

Q1: How do you cut your own hair?
Q2: Are you cheap if you cut your own hair?
Actual: 0.0
Pred: True

Q1: What ages go with each grade in America?
Q2: What might happen now that President-elect Donald Trump has won the election? What will be the impact?
Actual: 0.0
Pred: True

Q1: Can "do better" mean "to get better"?
Q2: Can "do better" mean to get better?
Actual: 1.0
Pred: False

Q1: I inserted a small stick in my penis. what will happen?
Q2: What shouldIdo it my penis is small?
Actual: 0.0
Pred: True

Q1: When did you realise you have grown up?
Q2: When did you realize that you were all grown up?
Actual: 0.0
Pred: True

Q1: What is the difference between Keynesian and classical economics?
Q2: What are the difference between Classical and Keynesian models in macroeconomics?
Actual: 0.0
Pred: True

### **Observed Limitations of LSTM for Semantic Similarity:**

- Surface word overlap bias

- Weak paraphrase recognition

- Negation handling difficulty

- Long sequence information loss

- Topic vs intent confusion